---
# This playbook setups up a workstation

# REVIST; some anomalies were encountered when combing Common / Developer configs, 
# easiest appaorcah (for now) was to create two blocks (fugly)

- name: Common configuration for VirtualBox/AWS EC2 nodes
  hosts: all #virtualbox, aws_ec2           
  gather_facts: true
  roles:
    - role: common
  tags: ['never', 'common']

- name: Developer configuration for VirtualBox/AWS EC2 nodes
  hosts: all #virtualbox, aws_ec2            
  gather_facts: true
  roles:
    - role: developer
  tags: ['never', 'developer']

- name: Start, stip or get info against aws_ec2 nodes
  hosts: aws_ec2
  gather_facts: false   # No need to gather (ssh) facts for aws_ec2 nodes/roles
  connection: local
  roles:
    - role: ../aws_ec2/roles/aws_ec2_instance_start
      tags:
        - aws_ec2_instance_start
    - role: ../aws_ec2/roles/aws_ec2_instance_info
      tags:
        - aws_ec2_instance_info
    - role: ../aws_ec2/roles/aws_ec2_instance_stop
      tags:
        - aws_ec2_instance_stop