---

- name: aws ec2 group terminate block
  block: 

    - name: aws ec2 group terminate 
      amazon.aws.ec2_group:
        state: 'absent'
        group_id: "{{ aws_ec2_group_id }}"
          
      register: result_terminate
    
    - name: aws ec2 group terminate - status
      debug:
        msg: 
          - "Termination Status: {{ result_terminate.changed }}"
  tags: ['never', 'aws_ec2_group_termimate']