---

- name: aws ec2 group terminate block
  block:

    - name: "User Input required: var: aws_ec2_group_id not defined"
      block: 

        - name: "User Input please enter Security Group ID:" 
          pause: 
            prompt: "Group ID (ie: sg-abc123)"
          register: prompt

        - name: set fact
          set_fact: 
            aws_ec2_group_id:  "{{ prompt.user_input }}"

        - name: debug 
          debug:
            msg: 
              - "prompt: {{prompt}}"
              - "var: {{ aws_ec2_group_id }}"
      when: 
        - aws_ec2_group_id is undefined
        
    - name: "aws ec2 group terminate: {{ aws_ec2_group_id }}" 
      amazon.aws.ec2_group:
        state: 'absent'
        group_id: "{{ aws_ec2_group_id }}"
          
      register: result_terminate
    
    - name: aws ec2 group terminate - status
      debug:
        msg: 
          - "Termination Status: {{ result_terminate.changed }}"

  tags: ['never', 'aws_ec2_group_termimate']