---

 - name: Run apt update (present)
   become: true
   apt:
     update_cache: true
     dpkg_options: 'force-confold,force-confdef'

 - name: Add PPA's
   become: true
   apt_repository: 
     repo: "{{ item.repo }}"
     filename: "{{ item.filename }}"
     update_cache: true
   loop:
     "{{ ppa_repo }}"
   when: 
     - ansible_distribution == ubuntu_distribution
   notify: Error Handler
 
 - name: Add Google Chrome Repo block
   become: true
   block:
 
   - name: Add Google Chrome Repo Signing Key 
     apt_key:
       url: "{{ chrome_repo_key }}"
       state: present
     notify: Error Handler
   
   - name: Add Google Chrome Repo
     apt_repository: 
       repo: "{{ chrome_repo }}"
       filename: google
       update_cache: true
     notify: Error Handler

   when:
     - ansible_distribution == ubuntu_distribution
     - ansible_architecture == architecture_x64
     - not host_is_headless                         # Only install on non headless machines

 - name: Install APT Packages
   become: true
   apt:
     name: "{{ item.name }}" 
     cache_valid_time: 600
     autoclean: true
     autoremove: true
     state: latest
   loop:
     "{{ common_apt_packages }}"
   when:
     - ansible_distribution == ubuntu_distribution

 #- name: check for python 2.7
 #  stat: 
 #    path: /usr/bin/python2.7
 #  register: pytnon_2_7

 #- name: check for python 3.6
 #  stat: path=/usr/bin/python3.6
 #  register: pytnon_3_6

 #- name: Configure update-alternatives for python 2.7
 #  become: true
 #  alternatives:
 #    link: "/usr/bin/{{ item.link }}"
 #    name: "{{ item.link }}"
 #    path: "/usr/bin/{{ item.path }}"
 #    priority: "{{ item.priority }}"
 #  loop: 
 #    "{{ update_alternatives_python_2_7 }}"
 #  when:
 #    - pytnon_2_7.stat.exists
 #    - ansible_distribution == ubuntu_distribution
 #  # we can ignore errors here, it just means not all the versuons of Python are installed. 
 #  #ignore_errors: true

 #- name: Configure update-alternatives for python 3.6
 #  become: true
 #  alternatives:
 #    link: "/usr/bin/{{ item.link }}"
 #    name: "{{ item.link }}"
 #    path: "/usr/bin/{{ item.path }}"
 #    priority: "{{ item.priority }}"
 #  loop: 
 #    "{{ update_alternatives_python_3_6 }}"
 #  when:
 #    - pytnon_3_6.stat.exists
 #    - ansible_distribution == ubuntu_distribution
 #  # we can ignore errors here, it just means not all the versuons of Python are installed. 
 #  #ignore_errors: true

 #- name: Configure update-alternatives for python 3.8
 #  become: true
 #  alternatives:
 #    link: "/usr/bin/{{ item.link }}"
 #    name: "{{ item.link }}"
 #    path: "/usr/bin/{{ item.path }}"
 #    priority: "{{ item.priority }}"
 #  loop: 
 #    "{{ update_alternatives_python_3_8 }}"
 #  when:
 #    # - pytnon_3_8.stat.exists                       #No need for this condition, installed in apt section above. 
 #    - ansible_distribution == ubuntu_distribution
 #  # we can ignore errors here, it just means not all the versuons of Python are installed. 
 #  #ignore_errors: true

 - name: Clone Bash_Scripts Repo from GitHub
   git: 
     repo: https://github.com/fidoedidoe/bash_scripts.git
     version: master
     dest: ~/bash_scripts
   when:
     - ansible_distribution == ubuntu_distribution

 - name: run apt-update-plus-cleanup.sh
   become: true
   command: "/home/{{ ansible_user_id }}/bash_scripts/apt-update-plus-cleanup.sh --no-prompt"
   when:
     - ansible_distribution == ubuntu_distribution

 - name: Copy Vim configuration 
   copy:
     src: .vimrc.j2 
     dest: ~/.vimrc
     mode: u=rw,g=r,o=r

 - name: Copy BashRC template 
   template:
     src: .bashrc.j2
     dest: ~/.bashrc
     mode: u=rw,g=r,o=r
   when:
     - ansible_distribution == ubuntu_distribution
