---
# tasks file for aws_instance_provision

- name: gather aws info (facts)
  block: 

    - name: Get instances info
      community.aws.ec2_instance_info:
        region: "{{ region }}"
      register: result

    - name: Instances ID
      debug:
        msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
      loop: "{{ result.instances }}"

  #tags: always
  tags: ['never', 'aws_gather_info']

- name: provision ec2 instance block 
  block: 

    - name: Provision ec2 instance(s)
      community.aws.ec2_instance:
        key_name: Ubuntu-Test-EC2
        security_groups: 
          - sg-001d137bb721caa35
        image_id: ami-05c424d59413a2876  #Ubuntu 20.04 t2.micro (free tier)
        instance_type: t2.micro
        region: "{{ region }}"
        wait: true
        tags:
          name: Ubuntu Test EC2 Micro (free)
          storage: 8GB
        volumes: 
          - device_name: /dev/sda1
            ebs: 
              delete_on_termination: yes
              volume_size: 8
              volume_type: gp2           # General Purpose SSD (gp2)
      register: result_provision

    - name: Instance ID
      debug:
        msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
      loop: "{{ result_provision.instances }}"

  tags: ['never', 'aws_provision_ec2']

- name: Terminate ec2 instance block
  block: 

    - name: terminate ec2 instances 
      community.aws.ec2_instance:
        state: 'absent'
        filters: 
          "tag:name": Ubuntu Test EC2 Micro (free)
      register: result_terminate
      
    - name: Instance ID
      debug:
        msg: "ID: {{ item.instance_id }} ; Type: {{ item.instance_type }} ; State: {{ item.state.name }}"
      loop: "{{ result_terminate.instances }}"

  tags: ['never', 'aws_termimate_ec2']
  
