---

 - name: Run apt update (present)
   become: true
   apt:
     update_cache: true
     dpkg_options: 'force-confold,force-confdef'

 - name: Add PPA's
   become: true
   apt_repository: 
     repo: "{{ item.repo }}"
     filename: "{{ item.filename }}"
     update_cache: true
   loop:
     "{{ ppa_repo }}"
   when: 
     - ansible_distribution == ubuntu_distribution
   notify: Error Handler
 
 - name: Add Google Chrome Repo block
   become: true
   block:
 
   - name: Add Google Chrome Repo Signing Key 
     apt_key:
       url: "{{ chrome_repo_key }}"
       state: present
     notify: Error Handler
   
   - name: Add Google Chrome Repo
     apt_repository: 
       repo: "{{ chrome_repo }}"
       filename: google
       update_cache: true
     notify: Error Handler

   when:
     - ansible_distribution == ubuntu_distribution
     - ansible_architecture == architecture_x64
     - not host_is_headless                         # Only install on non headless machines

 - name: Install APT Packages
   become: true
   apt:
     name: "{{ item.name }}" 
     cache_valid_time: 600
     autoclean: true
     autoremove: true
     state: latest
   loop:
     "{{ common_apt_packages }}"
   when:
     - ansible_distribution == ubuntu_distribution

 - name: Configure update-alternatives for python 2.x/3.x
   become: true
   alternatives:
     link: "/usr/bin/{{ item.link }}"
     name: "{{ item.link }}" 
     path: "/usr/bin/{{ item.path }}"
     priority: "{{ item.priority }}"
   loop: 
     "{{ update_alternatives_python }}"
   when:
     - ansible_distribution == ubuntu_distribution
   # we can ignore errors here, it just means not all the versuons of Python are installed. 
   ignore_errors: true

 - name: Clone Bash_Scripts Repo from GitHub
   git: 
     repo: https://github.com/fidoedidoe/bash_scripts.git
     version: master
     dest: ~/bash_scripts
   when:
     - ansible_distribution == ubuntu_distribution

 - name: run apt-update-plus-cleanup.sh
   become: true
   command: "/home/{{ ansible_user_id }}/bash_scripts/apt-update-plus-cleanup.sh --no-prompt"
   when:
     - ansible_distribution == ubuntu_distribution

 - name: Copy Vim configuration 
   copy:
     src: .vimrc.j2 
     dest: ~/.vimrc
     mode: u=rw,g=r,o=r

 - name: Copy BashRC template 
   template:
     src: .bashrc.j2
     dest: ~/.bashrc
     mode: u=rw,g=r,o=r
   when:
     - ansible_distribution == ubuntu_distribution
