---
# This playbook setups up a workstation

- name: Common configuration for VirtualBox nodes
  #hosts: all            
  hosts: virtualbox
  gather_facts: true
  roles:
    - role: common
      tags:
        - common
    - role: developer
      tags: 
        - developer

- name: start aws_ec2 nodes
  hosts: aws_ec2
  gather_facts: false                 # No need to gather (ssh) facts for aws_ec2 nodes
  roles:
    - role: common
      tags:
        - common
    - role: developer
      tags: 
        - developer
    - role: aws_instance_start
      tags:
        - aws_start
    - role: aws_instance_gather_info
      tags:
        - aws_gather_info
    - role: aws_instance_stop
      tags:
        - aws_stop
